# Generated by Django 5.2.16 on 2026-07-10 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationtask',
            name='task_type',
            field=models.CharField(choices=[('outline', 'Outline'), ('script', 'Script'), ('episode_script', 'Episode script'), ('storyboard', 'Storyboard'), ('character_profile', 'Character profile'), ('character_image', 'Character image')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=255)),
                ('appearance', models.TextField()),
                ('personality', models.TextField(blank=True)),
                ('costume', models.TextField(blank=True)),
                ('image_prompt', models.TextField()),
                ('position', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='studio.script')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CharacterAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=120)),
                ('prompt_snapshot', models.TextField()),
                ('image', models.FileField(upload_to='characters/%Y/%m/%d')),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.character')),
            ],
            options={
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('script', 'name'), name='unique_character_name_per_script'),
        ),
        migrations.AddConstraint(
            model_name='characterasset',
            constraint=models.UniqueConstraint(fields=('character', 'version'), name='unique_character_asset_version'),
        ),
    ]
