# Generated by Django 5.2.16 on 2026-07-13 04:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_script_character_visual_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('model_id', models.CharField(max_length=160)),
                ('capability', models.CharField(choices=[('text', 'Text generation'), ('image', 'Image generation'), ('video_reference', 'Reference-to-video'), ('video_image', 'Image-to-video'), ('video_edit', 'Video editing')], db_index=True, max_length=40)),
                ('default_parameters', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['capability', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('provider_type', models.CharField(choices=[('openai_compatible', 'OpenAI compatible'), ('dashscope', 'Aliyun Bailian / DashScope')], max_length=32)),
                ('base_url', models.URLField(max_length=500)),
                ('api_key_env_var', models.CharField(default='DASHSCOPE_API_KEY', max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=600)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('max_concurrency', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('outline', '大纲生成'), ('script', '剧本规划'), ('episode_script', '分集剧本'), ('character_profile', '角色设定'), ('storyboard', '分镜生成'), ('character_image', '角色图片'), ('shot_video', '分镜视频主模型'), ('shot_video_fallback', '分镜视频备用模型'), ('video_edit', '视频编辑')], max_length=48, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='studio.modelconfig')),
            ],
            options={
                'ordering': ['purpose'],
            },
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='studio.providerconfig'),
        ),
        migrations.CreateModel(
            name='StoryboardShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('shot_number', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField(default=5)),
                ('duration_label', models.CharField(blank=True, max_length=60)),
                ('visual_description', models.TextField(blank=True)),
                ('character_action', models.TextField(blank=True)),
                ('dialogue_or_narration', models.TextField(blank=True)),
                ('camera_language', models.TextField(blank=True)),
                ('image_prompt', models.TextField(blank=True)),
                ('video_prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('character_names', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='studio.storyboardprompt')),
            ],
            options={
                'ordering': ['position', 'shot_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShotCharacterReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shot_references', to='studio.characterasset')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_references', to='studio.character')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_references', to='studio.storyboardshot')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('submitting', 'Submitting'), ('running', 'Running'), ('downloading', 'Downloading'), ('ready', 'Ready'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='queued', max_length=24)),
                ('provider_task_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('provider_request_id', models.CharField(blank=True, max_length=160)),
                ('input_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('prompt_snapshot', models.TextField()),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(blank=True, max_length=1500)),
                ('video', models.FileField(blank=True, upload_to='videos/shots/%Y/%m/%d')),
                ('error_message', models.TextField(blank=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('generation_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_asset', to='studio.generationtask')),
                ('model_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='video_assets', to='studio.modelconfig')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_assets', to='studio.storyboardshot')),
            ],
            options={
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VideoComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('exporting', 'Exporting'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=24)),
                ('video', models.FileField(blank=True, upload_to='videos/exports/%Y/%m/%d')),
                ('error_message', models.TextField(blank=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_composition', to='studio.episode')),
            ],
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.UniqueConstraint(fields=('provider', 'model_id', 'capability'), name='unique_provider_model_capability'),
        ),
        migrations.AddConstraint(
            model_name='storyboardshot',
            constraint=models.UniqueConstraint(fields=('storyboard', 'shot_number'), name='unique_storyboard_shot_number'),
        ),
        migrations.AddConstraint(
            model_name='shotcharacterreference',
            constraint=models.UniqueConstraint(fields=('shot', 'character'), name='unique_character_per_shot'),
        ),
        migrations.AddConstraint(
            model_name='videoasset',
            constraint=models.UniqueConstraint(fields=('shot', 'version'), name='unique_shot_video_version'),
        ),
    ]
