# Generated by Django 5.2.16 on 2026-07-15 03:49

import django.db.models.deletion
import studio.video_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_simple_model_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocomposition',
            options={'ordering': ['-version', '-id']},
        ),
        migrations.AddField(
            model_name='videocomposition',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='video',
            field=models.FileField(blank=True, upload_to=studio.video_models.shot_video_upload_to),
        ),
        migrations.AlterField(
            model_name='videocomposition',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_compositions', to='studio.episode'),
        ),
        migrations.AlterField(
            model_name='videocomposition',
            name='video',
            field=models.FileField(blank=True, upload_to=studio.video_models.composition_video_upload_to),
        ),
        migrations.AddConstraint(
            model_name='videocomposition',
            constraint=models.UniqueConstraint(fields=('episode', 'version'), name='unique_episode_export_version'),
        ),
    ]
