# Generated by Django 5.2.16 on 2026-07-23 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0019_remove_shotsubtitlesetting_style_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('worker_id', models.CharField(blank=True, default='', max_length=160)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('retryable', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['attempt_number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='generationtask',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='error_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='lease_owner',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='priority',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='progress_current',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationtask',
            name='progress_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generationtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('retry_wait', 'Retry wait'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddIndex(
            model_name='generationtask',
            index=models.Index(fields=['status', 'next_retry_at', 'priority', 'created_at'], name='generation_task_queue_idx'),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='studio.generationtask'),
        ),
        migrations.AddConstraint(
            model_name='generationattempt',
            constraint=models.UniqueConstraint(fields=('task', 'attempt_number'), name='unique_generation_attempt_number'),
        ),
    ]
