# Generated by Django 5.2.16 on 2026-07-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0023_acfun_publishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitletrack',
            name='qc_ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='qc_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='qc_content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='qc_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='qc_reason',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='qc_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='qc_rule_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='qc_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtitletrack',
            name='qc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='modelassignment',
            name='purpose',
            field=models.CharField(choices=[('outline', '大纲生成'), ('script', '剧本规划'), ('episode_script', '分集剧本'), ('character_profile', '角色设定'), ('storyboard', '分镜生成'), ('subtitle_qc', '字幕质检'), ('character_image', '角色图片'), ('shot_video', '分镜视频主模型'), ('shot_video_fallback', '分镜视频备用模型'), ('video_edit', '视频编辑')], max_length=48, unique=True),
        ),
    ]
