# Generated by Django 5.2.16 on 2026-07-28 12:24

import django.db.models.deletion
from django.db import migrations, models


def backfill_cover_template_versions(apps, schema_editor):
    CoverTemplate = apps.get_model("studio", "CoverTemplate")
    CoverTemplateVersion = apps.get_model("studio", "CoverTemplateVersion")
    for template in CoverTemplate.objects.exclude(background="").iterator():
        CoverTemplateVersion.objects.get_or_create(
            template_id=template.id,
            version=template.version,
            defaults={
                "prompt_snapshot": template.prompt_snapshot,
                "background": template.background.name,
                "source_url": template.source_url,
                "model": template.model,
                "style_payload": template.style_payload,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0025_douyin_publishing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_snapshot', models.TextField()),
                ('background', models.FileField(upload_to='covers/templates/%Y/%m/%d')),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('model', models.CharField(max_length=120)),
                ('style_payload', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='studio.covertemplate')),
            ],
            options={
                'ordering': ['-version', '-id'],
                'constraints': [models.UniqueConstraint(fields=('template', 'version'), name='unique_cover_template_version')],
            },
        ),
        migrations.RunPython(
            backfill_cover_template_versions,
            migrations.RunPython.noop,
        ),
    ]